name: assembleDebug
on: [push, pull_request]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: "-Dorg.gradle.jvmargs=-Xmx8g :module21:module02:assembleDebug"
